"""Initial migration.

Revision ID: 688fdea7f9f9
Revises: 
Create Date: 2024-09-10 15:17:26.843714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688fdea7f9f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('methods', sa.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kong_service_id', sa.String(length=36), nullable=True),
    sa.Column('kong_route_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('path'),
    sa.UniqueConstraint('url')
    )
    op.create_table('plugin',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plugin_api_configuration',
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('api_id', sa.String(length=36), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kong_plugin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.PrimaryKeyConstraint('plugin_id', 'api_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugin_api_configuration')
    op.drop_table('plugin')
    op.drop_table('api')
    # ### end Alembic commands ###
